---
name: Docker Build and Push
on:
  release:
    types: [created]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: jdrouet/docker-with-buildx:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

      - name: Build and push Docker images
        env:
          DOCKER_BUILDKIT: 1
          IMAGE_TAG: ${{ github.event.release.tag_name }}
          IMAGE_NAME: batch_remove_bg
        run: |
          docker buildx create --use --name multibuilder
          docker buildx build --push --tag "$DOCKER_HUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG" --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 .
